name: Release Github Action's Version's
on:
  push: {}

jobs:
  release:
    uses: Invasor-de-Fronteiras/github-actions/.github/workflows/reusable-release-github-action.yml@main
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance