name: Release Github Action
on:
  workflow_call: {}

jobs:
  discover:
    name: Discover reusable workflows
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      
      - id: set-matrix
        run: |
          set -e
          echo "Listing all reusable workflows..."

          # Lista TODOS os arquivos reusable-*.yml
          workflow_files=$(ls .github/workflows/reusable-*.yml 2>/dev/null || true)

          normalized_files=$(echo "$workflow_files" \
            | sed 's#.github/workflows/##' \
            | sed 's/\.yml$//')

          files=$(echo "$normalized_files" | tr '\n' ' ' | xargs || true)

          echo "found: $files"

          if [ -z "$files" ]; then
            echo "No reusable workflows found"
            echo 'matrix={"workflow":[]}' >> "$GITHUB_OUTPUT"
            exit 0
          fi

          json=$(printf '%s\n' $files | jq -R . | jq -cs '{ workflow: . }')

          echo "matrix=$json" >> "$GITHUB_OUTPUT"
  release:
    needs: discover
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}
    name: Release ${{ matrix.workflow }}
    uses: Invasor-de-Fronteiras/github-actions/.github/workflows/reusable-release.yml@main
    with:
      release-config-content: |
        {
          "branches": [
            "main",
            "next",
            "beta"
          ],
          "tagFormat": "${{ matrix.workflow }}-v${version}",
          "plugins": [
            [
              "@semantic-release/commit-analyzer",
              {
                "preset": "conventionalcommits",
              }
            ],
            "@semantic-release/release-notes-generator",
            [
              "@semantic-release/changelog",
              {
                "changelogFile": "docs/workflows/${{ matrix.workflow }}.CHANGELOG.md"
              }
            ],
            [
              "semantic-release-major-tag",
              {
                "customTags": ["${{ matrix.workflow }}-v${major}"]
              }
            ],
            [
              "@semantic-release/git",
              {
                "assets": [
                  "docs/workflows/${{ matrix.workflow }}.CHANGELOG.md",
                  "docs/workflows/${{ matrix.workflow }}.md",

                ],
                "message": "chore(release): ${{ matrix.workflow }}-v${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
              }
            ]
          ],

        }
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    secrets: inherit
