name: Release Tag
on:
  workflow_call:
    inputs:
      packages:
        required: false
        type: string
        default: "@semantic-release/commit-analyzer,@semantic-release/changelog,@semantic-release/git,@semantic-release/github,conventional-changelog-conventionalcommits"
      create-release-config:
        required: false
        type: boolean
        default: true
      release-config-content:
        required: false
        type: string
        default: |
          {
            "branches": [
              "main",
              "next",
              "beta"
            ],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/changelog",
              "@semantic-release/git",
            ]
          }

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - name: Create .releaserc
        if: ${{ inputs.create-release-config }}
        env:
          RELEASE_CONFIG_CONTENT: ${{ inputs.release-config-content }}
        run: |
          if [ -f .releaserc ]; then
            echo ".releaserc already exists"
            cat .releaserc
            exit 0
          fi

          echo '$RELEASE_CONFIG_CONTENT' > .releaserc
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: ${{ inputs.packages }}
        run: |
          set -e
          
          EXTRA_PACKAGES=""
          IFS=',' read -ra PKGS <<< "$PACKAGES"
          for pkg in "${PKGS[@]}"; do
            EXTRA_PACKAGES="$EXTRA_PACKAGES --package $pkg"
          done

          echo "Using packages: $EXTRA_PACKAGES"

          npx --package semantic-release $EXTRA_PACKAGES semantic-release