name: Release Tag
on:
  workflow_call:
    inputs:
      packages:
        required: false
        type: string
        default: |
          semantic-release-major-tag
          @semantic-release/release-notes-generator
          @semantic-release/commit-analyzer
          @semantic-release/changelog
          @semantic-release/git
          @semantic-release/github
          conventional-changelog-conventionalcommits
      create-release-config:
        required: false
        type: boolean
        default: true
      create-branch:
        required: false
        type: boolean
        default: false
      branch-name:
        required: false
        type: string
        default: 'release/${{ github.ref_name }}'
      branch-to:
        required: false
        type: string
        default: 'release'
      release-config-content:
        required: false
        type: string
        default: |
          {
            "branches": [
              "main",
              "next",
              "beta"
            ],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/changelog",
              "@semantic-release/git"
            ]
          }

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Create ${{ inputs.branch-to }} branch if it does not exist
        if: ${{ inputs.create-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_TO: ${{ inputs.branch-to }}
        run: |
          set -e

          echo "Creating $BRANCH_TO branch if it does not exist"
          if git rev-parse --verify origin/$BRANCH_TO >/dev/null 2>&
          then
            echo "Branch $BRANCH_TO already exists"
          else
            echo "Branch $BRANCH_TO does not exist. Creating it from main."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b $BRANCH_TO origin/main
            git push origin $BRANCH_TO
          fi

      - name: Create ${{ inputs.branch-name }} branch
        if: ${{ inputs.create-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ inputs.branch-name }}
          BRANCH_TO: ${{ inputs.branch-to }}
        run: |
          set -e

          echo "Creating $BRANCH_NAME branch from $BRANCH_TO"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH_NAME origin/$BRANCH_TO
          git push origin $BRANCH_NAME

      - name: Create .releaserc
        if: ${{ inputs.create-release-config }}
        env:
          RELEASE_CONFIG_CONTENT: ${{ inputs.release-config-content }}
        run: |
          if [ -f .releaserc ]; then
            echo ".releaserc already exists"
            cat .releaserc
            exit 0
          fi

          echo $RELEASE_CONFIG_CONTENT > .releaserc

          echo "Created .releaserc with content:\n"
          cat .releaserc
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: ${{ inputs.packages }}
        run: |
          set -e
          
          NORMALIZED_PKGS=$(echo $PACKAGES | tr '\n' ',' | sed 's/,$//')
          echo "Normalized packages: $NORMALIZED_PKGS"

          EXTRA_PACKAGES=""
          read -ra PKGS <<< "$NORMALIZED_PKGS"
          for pkg in "${PKGS[@]}"; do
            EXTRA_PACKAGES="$EXTRA_PACKAGES --package $pkg"
          done

          echo "Using packages: $EXTRA_PACKAGES"

          npx --package semantic-release $EXTRA_PACKAGES semantic-release

